# Generated by Django 6.0.6 on 2026-08-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblContractor',
            fields=[
                ('id_contractor', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('trade_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_license_expiry', models.DateField(blank=True, null=True)),
                ('vat_trn', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_contractor',
            },
        ),
        migrations.CreateModel(
            name='TblContractStatus',
            fields=[
                ('id_contract_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_contract_status',
            },
        ),
        migrations.CreateModel(
            name='TblPpmStatus',
            fields=[
                ('id_ppm_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_ppm_status',
            },
        ),
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(max_length=50)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='TblContractDetails',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('contract_ref_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('no_of_ppms', models.IntegerField()),
                ('ppm_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('next_ppm_schedule', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('contract_document', models.TextField(blank=True, null=True)),
                ('renewal_reminder_days', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_contractor', models.ForeignKey(blank=True, db_column='id_contractor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblcontractor')),
                ('id_contract_status', models.ForeignKey(blank=True, db_column='id_contract_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblcontractstatus')),
            ],
            options={
                'db_table': 'tbl_contract_details',
            },
        ),
        migrations.CreateModel(
            name='TblRegion',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblregion')),
            ],
            options={
                'db_table': 'tbl_region',
            },
        ),
        migrations.CreateModel(
            name='TblSite',
            fields=[
                ('id_site', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('server_count', models.IntegerField()),
                ('camera_count', models.IntegerField()),
                ('current_software', models.CharField(blank=True, max_length=100, null=True)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('site_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('site_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sira_connected', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_region', models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblregion')),
                ('allocated_site_engineer', models.ForeignKey(blank=True, db_column='allocated_site_engineer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers')),
            ],
            options={
                'db_table': 'tbl_site',
            },
        ),
        migrations.CreateModel(
            name='TblPpmSchedule',
            fields=[
                ('id_ppm', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('engineer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('report_document', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblcontractdetails')),
                ('id_ppm_status', models.ForeignKey(blank=True, db_column='id_ppm_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblppmstatus')),
                ('id_site', models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblsite')),
                ('id_assigned_user', models.ForeignKey(blank=True, db_column='id_assigned_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers')),
            ],
            options={
                'db_table': 'tbl_ppm_schedule',
            },
        ),
        migrations.CreateModel(
            name='TblEquipmentDetails',
            fields=[
                ('id_equipment_det', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_sl_no', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('cam_firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('licen_expiry', models.DateField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.TextField(blank=True, null=True)),
                ('location_in_site', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField()),
                ('last_audited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_site', models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblsite')),
            ],
            options={
                'db_table': 'tbl_equipment_details',
            },
        ),
        migrations.AddField(
            model_name='tblcontractdetails',
            name='id_site',
            field=models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblsite'),
        ),
        migrations.CreateModel(
            name='TblNotifications',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=50)),
                ('ref_table', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers')),
            ],
            options={
                'db_table': 'tbl_notifications',
            },
        ),
        migrations.CreateModel(
            name='TblDocuments',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=50)),
                ('ref_table', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField()),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers')),
            ],
            options={
                'db_table': 'tbl_documents',
            },
        ),
        migrations.AddField(
            model_name='tblcontractdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers'),
        ),
        migrations.CreateModel(
            name='TblAuditLog',
            fields=[
                ('id_audit', models.AutoField(primary_key=True, serialize=False)),
                ('audit_date', models.DateField()),
                ('findings', models.TextField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('audit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('follow_up_required', models.BooleanField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('report_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id_ppm', models.ForeignKey(blank=True, db_column='id_ppm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblppmschedule')),
                ('id_site', models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblsite')),
                ('audited_by', models.ForeignKey(blank=True, db_column='audited_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers')),
            ],
            options={
                'db_table': 'tbl_audit_log',
            },
        ),
        migrations.CreateModel(
            name='TblActivityLog',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('logged_at', models.DateTimeField()),
                ('id_user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amc_app.tblusers')),
            ],
            options={
                'db_table': 'tbl_activity_log',
            },
        ),
    ]
